name: resume
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_builder: ^0.2.0+2
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  flutter_rounded_progress_bar: ^0.1.2
  url_launcher: ^5.5.0
  url_launcher_web: ^0.1.2
  characters: ^1.0.0
  get_it: ^4.0.2
  adaptive_theme: ^1.0.0
  scroll_to_index: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Agustina
      fonts:
        - asset: assets/fonts/Agustina.ttf